#判断pm2服务是否安装
- block:
  - name: Configure | Judge install {{ PM2_SERVICE }}
    command: pm2 describe {{ PM2_SERVICE }}
    register: pm2_install_result
    ignore_errors: True

  - name: Configure | Start {{ PM2_SERVICE }}
    shell:
      cd {{ CODE_PATH }};pm2 -n {{ PM2_SERVICE }} start server.js
    when: pm2_install_result.rc

  #启动服务
  - name: Configure | ReStart {{ PM2_SERVICE }}
    shell:
      pm2 restart {{ PM2_SERVICE }}
  when: USE_SCRIPT != "TRUE"
    
- name: Configure | RUN PM2_SERVICE
  shell:
    /bin/bash {{ CODE_PATH }}/script/run-stage.sh
  when: USE_SCRIPT == "TRUE"